#! /bin/sh

sxhkd &

bspc monitor -d i ii iii iv v vi vii

# layouts
bspc desktop " i "      -l monocle
bspc desktop " ii "     -l monocle
bspc desktop " iii "    -l monocle
bspc desktop " iv "     -l monocle

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Emacs desktop=^1
bspc rule -a Terminator desktop=^2
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

emacs &
terminator &

# panel &
$HOME/.config/polybar/launch_polybar.sh
