#! /bin/sh

sxhkd &

# bspc monitor -d i ii iii iv v vi vii
# bspc monitor DP2 -d i ii iii iv v vi vii viii
bspc monitor DP2 -d 1 2 3 4 5 6 7 8
# bspc monitor VGA-2 -d v vi vii viii

# layouts
bspc desktop " i "      -l monocle
bspc desktop " ii "     -l monocle
bspc desktop " iii "    -l monocle
bspc desktop " iv "     -l monocle

bspc config border_width         2
bspc config focused_border_color "#859900"
bspc config active_border_color  "#859900"
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Mouse control
#bspc config focus_follows_pointer true
bspc config click_to_focus button1

# Startup programs (some using one-shot rules)
bspc rule -a Emacs desktop=^1 state=tiled -o; emacs &
bspc rule -a Terminator desktop=^2 -o; terminator -e "mux start dev" &
bspc rule -a HipChat desktop=^3; hipchat4 &
bspc rule -a Synergy desktop=^8; synergy &

# Rules
bspc rule -a Firefox desktop=^6

# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# Launch bar
$HOME/.config/polybar/launch_polybar.sh

