hook global InsertChar k %{ try %{
  exec -draft hH <a-k>kj<ret> d
  exec <esc>
}}

source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andreyorst/fzf.kak"
plug "danr/kakoune-easymotion"
plug "h-youhei/kakoune-surround"
plug "andreyorst/smarttab.kak" defer smarttab %{
        # when `backspace' is pressed, 4 spaces are deleted at once
        set-option global softtabstop 4
        } config %{
            # these languages will use `expandtab' behavior
            hook global WinSetOption filetype=(rust|markdown|kak|lisp|scheme|sh|perl|c|cpp) expandtab
            # these languages will use `noexpandtab' behavior
            hook global WinSetOption filetype=(makefile|gas) noexpandtab
        }
plug "andreyorst/tagbar.kak" defer "tagbar" %{
	set-option global tagbar_sort false
	set-option global tagbar_size 40
	set-option global tagbar_display_anon false
} config %{
        # if you have wrap highlighter enamled in you configuration
        #     # files it's better to turn it off for tagbar, using this hook:
        #         hook global WinSetOption filetype=tagbar %{
            #                 remove-highlighter window/wrap
            #                         # you can also disable rendering whitespaces here, line numbers, and
            #                                 # matching characters
	}
}

# Enable line numbers globally
# add-highlighter global/ number-lines

# Automatically wrap lines
add-highlighter global/ wrap

map global normal <c-p> ': fzf-mode<ret>'
map global normal <c-k> ': comment-line<ret>'
